name: Build

on:
  pull_request:
  workflow_dispatch:

permissions:
  checks: write
  contents: read

jobs:
  build:
    name: Build (${{ matrix.target }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target: [ bootloader, installer, signer ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6

      - name: Install build tools
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: clang cmake ninja-build lld

      - name: Build project
        run: ./ci/build-${{ matrix.target }}.sh
        shell: bash